### ISSUE TITLE
SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by ferferga** [tjx666/unplugin-detect-duplicated-deps#2]
Hello, I'm just trying this plugin with Vite in [this project](https://github.com/jellyfin/jellyfin-vue). I'm simply using a GitHub Codespace created from the template of that repository (in case you want to check with the exact same environment) in master branch.

I receive the following stacktrace:

```
failed to load config from /workspaces/jellyfin-vue/frontend/vite.config.ts
error during build:
/workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/chunk-7F7UDY64.js:12
var workspaceRootFolder = await _workspaceroot.workspaceRoot.call(void 0, );
                          ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at _require.extensions.<computed> [as .js] (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64435:17)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/vite.js:3:24)
```
Some other things:
* I'm not on latest vite, but I tried latest, with same result
* I added this plugin as the last to the list of plugins

**Comment by tjx666** [comment]
please test 0.1.2

**Comment by ferferga** [comment]
@tjx666 Unrelated to the original issue, but seems it was introduced by replacing mem with pmemoize:

```
error during build:
Error [ERR_REQUIRE_ESM]: require() of ES Module /workspaces/jellyfin-vue/node_modules/p-memoize/dist/index.js from /workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/chunk-7YDXDWTN.js not supported.
Instead change the require of index.js in /workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/chunk-7YDXDWTN.js to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64435:17)
    at Object.<anonymous> (/workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/chunk-7YDXDWTN.js:6:17)
    at _require.extensions.<computed> [as .js] (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64435:17)
    at Object.<anonymous> (/workspaces/jellyfin-vue/node_modules/unplugin-detect-duplicated-deps/dist/vite.js:3:24)
    at _require.extensions.<computed> [as .js] (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64435:17)
    at Object.<anonymous> (/workspaces/jellyfin-vue/frontend/vite.config.ts:51:28)
    at _require.extensions.<computed> [as .js] (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64432:24)
    at loadConfigFromBundledFile (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64440:21)
    at async loadConfigFromFile (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:64296:28)
    at async resolveConfig (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:63904:28)
    at async build (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/chunks/dep-a178814b.js:46267:20)
    at async CAC.<anonymous> (file:///workspaces/jellyfin-vue/node_modules/vite/dist/node/cli.js:812:9)
```

**Comment by tjx666** [comment]
you can try rename vite.config.ts to vite.config.mts

**Comment by tjx666** [comment]
I will try to fix the usage on node commonjs environment tonight

**Comment by ferferga** [comment]
@tjx666 Renaming worked wonderfully! Will try the new version once the fix is published and I think we can consider this issue solved then!

**Comment by tjx666** [comment]
try latest version 0.1.3
